// <auto-generated />
namespace DUTResManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Semester2UseCases : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Semester2UseCases));

        string IMigrationMetadata.Id
        {
            get { return "202607140900000_Semester2UseCases"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
