// <auto-generated />
namespace DUTResManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ConcludeEmergencyRollCall : IMigrationMetadata
    {
        private readonly ResourceManager Resources =
            new ResourceManager(typeof(ImprovedElectionWorkflow));

        string IMigrationMetadata.Id
        {
            get { return "202608091000000_ConcludeEmergencyRollCall"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}