// <auto-generated />
namespace DUTResManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class SyncUc08Uc16Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SyncUc08Uc16Model));
        
        string IMigrationMetadata.Id
        {
            get { return "202608101432115_SyncUc08Uc16Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
